Задача 1-2 решена в Julia #6
Arkii22/Informatics pull request #7
Opened 2021-05-19 20:43 UTC by Arkii22

###Что сделано
1. Написана программа в Julia

2021-05-20 21:27 UTC, MarinaPaley requested changes

2021-05-20 21:27 UTC, MarinaPaley commented on Work 1/Task 1-2(2).jl
> +      throw(StopException("Ошибка ввода данных"));
у меня говорит, что нет такого параметра `StopExeption`, замените на `ArgumentError`.
`quit();` - не нужен, до него не доходит дело, если выбрасывается исключение (у меня этот опертор не работал)

2021-05-20 21:27 UTC, MarinaPaley commented on Work 1/Task 1-2(2).jl
> + if y1==nothing
так же

2021-05-20 21:27 UTC, MarinaPaley commented on Work 1/Task 1-2(2).jl
> +       throw(StopException("Ошибка ввода данных"));
тоже

2021-05-25 18:44 UTC, Arkii22 commented
@MarinaPaley, исправила параметр

2021-05-25 18:57 UTC, MarinaPaley approved these changes
Уберите строку, а так - все хорошо

2021-05-25 18:57 UTC, MarinaPaley commented on Work 1/Task 1-2(3).jl
> +      quit();
эту строку уберите. Она не нужна (везде по коду)

2021-05-30 19:04 UTC, closed without merging