Решена задача 2-1 в Julia #8
Arkii22/Informatics pull request #9
Opened 2021-05-20 19:36 UTC by Arkii22

2021-05-20 21:31 UTC, MarinaPaley requested changes
как и в первом задании нужно заменить тип исключения на `ArgumentError`, а остальные две строки просто не нужны

2021-05-21 06:00 UTC, MarinaPaley requested changes
Очень Вас хвалю! Давайте в том же духе. Сдадите вовремя все работы- поставлю экзамен автоматом

2021-05-21 06:00 UTC, MarinaPaley commented on Work 2/Task 2-1(2).jl
> +user = tryparse(Float64, user_input);
Нужно в данном случае приводить к типу `Int`

2021-05-22 18:58 UTC, Arkii22 commented
Поменяла и исправила замечания, загрузила исправлены файлы в ту же ветку, но не уверена, что сделала это правильно

2021-06-21 20:14 UTC, MarinaPaley approved these changes
Правда, Вы неправильно работаете с системой контроля версий... У вас несколько версий одного файла. А должен быть только один файл(

2021-06-21 20:27 UTC, Arkii22 commented
А предыдущие версии нужно как-то удалять?
У меня почему-то часто случается, что удаляются вообще все файлы, даже те, что до этого были загружены, поэтому я исправляю и сохраняю их повторно

2021-06-21 20:29 UTC, MarinaPaley commented
Нет. Оставьте все так. Просто нужно открывать файл и менять его, работать с ним. А потом рушить. Не нужно создавать новые файлы

2021-06-21 20:38 UTC, merged